# generate vector table.

def p(s : str): print(s)
def pp(s : str): print("  " + s)

p("# DONT EDIT")
p("# generated by vector.py")
p(".global alltraps")

# generate traps
for i in range(0, 256):
    p(f".global vector{str(i)}")
    p(f"vector{str(i)}:")

    if not (i == 8 or (i >= 10 and i <= 14) or i == 17):
        pp(f"  push {0}")
    pp(f"  push {str(i)}")
    pp("  jmp alltraps")

# generate vector tables

p("# vector table")
p(".data vectors")
p("vectors:")

for i in range(0, 256):
    pp(f".long vector{str(i)}")
